### ISSUE TITLE
Add an option to add notes to the pull request body

### ISSUE THREAD

**Issue by davegaeddert** [dependencies-io/support#10]
Example here: https://github.com/percy/percy-web/pull/198

We've been considering adding a "setting" to all actors that use [pullrequest](https://github.com/dependencies-io/pullrequest) so that you could add you own content into the PR. "Notes"? "Additional content"? Not sure yet, but would look something like this:

```yaml
collectors:
- type: js-npm
  path: /
  actors:
  - type: js-npm
    settings:
      additional_content: >
        This is more text we want in every PR made by this actor...
```

**Comment by timhaines** [comment]
Thanks for logging this @davegaeddert!  For clarity, I'd like to be able to record a note per package.  In our use case, there's one or two packages we do some additional manual testing for.  Having the ability to record a note would ensure all team members got the right info at the right time.

**Comment by davegaeddert** [comment]
Yep, sorry I left that part out of the example I gave. In the current setup you'd just filter out the dependencies per actor... It'd a little more tedious, but that's how it works today and when you get that specific it's going to require some extra typing somewhere! When we get around to implementing this we'll make sure there's not a better way to do it (the `dependencies` filtering and inverse `dependencies_not_matching` is a little annoying).

```yaml
collectors:
- type: js-npm
  path: /
  actors:
  - type: js-npm
    dependencies: ember-power-selector
    settings:
      additional_content: >
        This is more text we want in every PR made by this actor...
  - type: js-npm
    dependencies_not_matching: ember-power-selector
```

**Comment by davegaeddert** [comment]
Hey @timhaines,

A little slow to get to this, but you can now use a `pullrequest_notes` setting to add your own notes to the top of the PR. Currently it works just like I mentioned in the last comment (except I changed the name of the setting). We do have plans though to let people specify the notes per dependency, without creating separate actors:
```yml
settings:
  pullrequest_notes:
    ember-power-selector: These are ember notes.
    another: This is another dependency.
```

There are a few changes I need to make first though before that will be possible. I'll close this issue but you can follow it here if you'd like: https://github.com/dependencies-io/pullrequest/issues/5
