### ISSUE TITLE
Build consistently fails for a specific directory/project

### ISSUE THREAD

**Issue by Vinnl** [dependencies-io/support#21]
I have a repository with four Node projects in it. Most of them work fine with dependencies.io, except for one, which appears to consistently fail in Yarn's "Linking dependencies" step:

```
Killed
/usr/src/actor/node_modules/shelljs/src/common.js:401
      if (config.fatal) throw e;
                        ^

Error: exec: internal error
    at Object.error (/usr/src/actor/node_modules/shelljs/src/common.js:110:27)
    at Object._exec (/usr/src/actor/node_modules/shelljs/src/exec.js:206:12)
    at Object.exec (/usr/src/actor/node_modules/shelljs/src/common.js:335:23)
    at /usr/src/actor/entrypoint.js:100:11
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/src/actor/entrypoint.js:34:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

An example of this output is [here](https://app.dependencies.io/projects/gitlab/Flockademic/Flockademic/builds/129) (though I'm guessing that's not publicly viewable?), the code of the specific Node project is [here](https://gitlab.com/Flockademic/Flockademic/tree/dev/stacks/frontend).

**Comment by davegaeddert** [comment]
Hey @Vinnl, it's a little odd that there isn't more information. I'm having trouble finding details on the backend too, but I'm wondering if it's using too many resources. Could you try updating your config temporarily to *only* update that stacks/frontend directory and see if it still fails?
```
collectors:
- type: js-npm
  path: stacks/frontend
  actors:
  # pull requests for updates to our major version
  - type: js-npm
    versions: "L.Y.Y"
  # create issues for new major versions
  - type: repo-issue
    versions: "Y.0.0"
```
Feel free to message me via support on dependencies.io to continue a more private conversation -- it's in the bottom right corner.
