### ISSUE TITLE
Provide rules or heuristics to skip some update PRs

### ISSUE THREAD

**Issue by greg-1-anderson** [dependencies-io/support#36]
Use case:

When using a Composer-based project, if I have an update that only includes "dev" dependencies (things I need to build / test my project, but do not need to run it), I would rather just skip the PR and not see it at all until there are also updates for non-dev dependencies.

Implementation:

dependencies.io would have to use `composer update --no-dev` to determine whether the PR should be made or not. If the PR should be made, though, then it should be constructed by running `composer update` without the `--no-dev` flag.

Is it possible for dependencies.io to use a different command to check if a PR is necessary than it uses to build the PR?

**Comment by davegaeddert** [comment]
Hey @greg-1-anderson, I think there would be a few different ways to get what you're looking for. We had plans at one point for a global "skip dev dependencies" kind of setting, but didn't finish pursuing it.

In the current PHP components, you could try using the `composer_options` setting to do this (untested):

```yml
- type: php
  settings:
    composer_options: "--no-dev"  # used in "collection", overriden when actually making updates
  lockfile_updates:
    settings:
      composer_options: ""
  manifest_updates:
    settings:
      composer_options: ""  
```
  
Admittedly not super straightforward, but not terrible if that seems to work. Let me know if you have any luck.
